-- Script de importação de usuários
-- Execute este arquivo no MySQL

INSERT INTO usuario (NMLOGIN, NOMEUSER, PERFIL, SENHA, LGATIVO) VALUES ('ABIGAIL', 'ABIGAIL (PRE)', 'USR', SHA2('temporaria123', 256), 1);
INSERT INTO usuario (NMLOGIN, NOMEUSER, PERFIL, SENHA, LGATIVO) VALUES ('ANDRE', 'ANDRE (PRE)', 'USR', SHA2('temporaria123', 256), 1);
INSERT INTO usuario (NMLOGIN, NOMEUSER, PERFIL, SENHA, LGATIVO) VALUES ('BEA.SC', 'BEA.SC (PRE)', 'USR', SHA2('temporaria123', 256), 1);
INSERT INTO usuario (NMLOGIN, NOMEUSER, PERFIL, SENHA, LGATIVO) VALUES ('BEATRIZ.SC', 'BEATRIZ.SC (PRE)', 'USR', SHA2('temporaria123', 256), 1);
INSERT INTO usuario (NMLOGIN, NOMEUSER, PERFIL, SENHA, LGATIVO) VALUES ('CURY.SC', 'CURY.SC (PRE)', 'USR', SHA2('temporaria123', 256), 1);
INSERT INTO usuario (NMLOGIN, NOMEUSER, PERFIL, SENHA, LGATIVO) VALUES ('IANDRAF.SC', 'IANDRAF.SC (PRE)', 'USR', SHA2('temporaria123', 256), 1);
INSERT INTO usuario (NMLOGIN, NOMEUSER, PERFIL, SENHA, LGATIVO) VALUES ('ISABEL.SC', 'ISABEL.SC (PRE)', 'USR', SHA2('temporaria123', 256), 1);
INSERT INTO usuario (NMLOGIN, NOMEUSER, PERFIL, SENHA, LGATIVO) VALUES ('LUIZ', 'LUIZ (PRE)', 'USR', SHA2('temporaria123', 256), 1);
INSERT INTO usuario (NMLOGIN, NOMEUSER, PERFIL, SENHA, LGATIVO) VALUES ('RYAN', 'RYAN (PRE)', 'USR', SHA2('temporaria123', 256), 1);
INSERT INTO usuario (NMLOGIN, NOMEUSER, PERFIL, SENHA, LGATIVO) VALUES ('TEIXEIRA', 'TEIXEIRA (PRE)', 'USR', SHA2('temporaria123', 256), 1);
INSERT INTO usuario (NMLOGIN, NOMEUSER, PERFIL, SENHA, LGATIVO) VALUES ('THEO', 'THEO (PRE)', 'USR', SHA2('temporaria123', 256), 1);
INSERT INTO usuario (NMLOGIN, NOMEUSER, PERFIL, SENHA, LGATIVO) VALUES ('TIAGOP', 'TIAGOP (PRE)', 'USR', SHA2('temporaria123', 256), 1);