<?php

return [
    '1000' => [
        'nome' => 'Controle de Patrimonio',
        'descricao' => 'Cadastro, consulta e termos de responsabilidade',
        'route' => 'patrimonios.index',
        'icone' => 'fa-cube',
        'cor' => 'blue',
        'ordem' => 1,
    ],
    '1001' => [
        'nome' => 'Gráficos',
        'descricao' => 'Indicadores e gráficos consolidados',
        'route' => 'dashboard',
        'icone' => 'fa-chart-line',
        'cor' => 'indigo',
        'ordem' => 2,
    ],
    '1009' => [
        'nome' => 'Removidos',
        'descricao' => 'Conferência de registros removidos',
        'route' => 'removidos.index',
        'icone' => 'fa-trash-can',
        'cor' => 'red',
        'ordem' => 3,
    ],
    '1007' => [
        'nome' => 'Histórico',
        'descricao' => 'Auditoria e trilha de movimentações',
        'route' => 'historico.index',
        'icone' => 'fa-clock-rotate-left',
        'cor' => 'violet',
        'ordem' => 4,
    ],
    '1002' => [
        'nome' => 'Locais',
        'descricao' => 'Cadastro de plantas, locais e vínculos',
        'route' => 'projetos.index',
        'icone' => 'fa-location-dot',
        'cor' => 'orange',
        'ordem' => 5,
    ],
    '1003' => [
        'nome' => 'Usuários',
        'descricao' => 'Gestão de contas, perfis e permissões',
        'route' => 'usuarios.index',
        'icone' => 'fa-users-cog',
        'cor' => 'cyan',
        'ordem' => 6,
    ],
    '1004' => [
        'nome' => 'Telas',
        'descricao' => 'Liberação e registro de novas telas',
        'route' => 'cadastro-tela.index',
        'icone' => 'fa-window-restore',
        'cor' => 'slate',
        'ordem' => 7,
    ],
    '1006' => [
        'nome' => 'Relatórios',
        'descricao' => 'Relatórios operacionais e exports',
        'route' => 'relatorios.patrimonios.gerar',
        'icone' => 'fa-file-lines',
        'cor' => 'amber',
        'ordem' => 8,
    ],
    '1008' => [
        'nome' => 'Tema',
        'descricao' => 'Preferências visuais e aparência',
        'route' => 'settings.theme',
        'icone' => 'fa-palette',
        'cor' => 'teal',
        'ordem' => 9,
    ],
];
