<?php

return [
    '1000' => [
        'nome' => 'Controle de Patrimonio',
        'descricao' => 'Cadastro, consulta e termos de responsabilidade',
        'route' => 'patrimonios.index',
        'icone' => 'fa-cube',
        'cor' => 'blue',
        'ordem' => 1,
    ],
    '1001' => [
        'nome' => 'Gráficos',
        'descricao' => 'Indicadores e graficos consolidados',
        'route' => 'dashboard',
        'icone' => 'fa-chart-line',
        'cor' => 'indigo',
        'ordem' => 2,
    ],
    '1002' => [
        'nome' => 'Cadastro de Locais',
        'descricao' => 'Cadastro de plantas, locais e vinculos',
        'route' => 'projetos.index',
        'icone' => 'fa-location-dot',
        'cor' => 'orange',
        'ordem' => 3,
    ],
    '1003' => [
        'nome' => 'Cadastro de Usuarios',
        'descricao' => 'Gestao de contas, perfis e permissoes',
        'route' => 'usuarios.index',
        'icone' => 'fa-users-cog',
        'cor' => 'cyan',
        'ordem' => 4,
    ],
    '1004' => [
        'nome' => 'Cadastro de Telas',
        'descricao' => 'Liberacao e registro de novas telas',
        'route' => 'cadastro-tela.index',
        'icone' => 'fa-window-restore',
        'cor' => 'slate',
        'ordem' => 5,
    ],
    '1005' => [
        'nome' => 'Gerenciar Acessos',
        'descricao' => 'Gestao de regras de acesso por usuario',
        'route' => null,
        'icone' => 'fa-key',
        'cor' => 'emerald',
        'ordem' => 6,
    ],
    '1006' => [
        'nome' => 'Relatorios',
        'descricao' => 'Relatorios operacionais e exports',
        'route' => 'relatorios.patrimonios.gerar',
        'icone' => 'fa-file-lines',
        'cor' => 'amber',
        'ordem' => 7,
    ],
    '1007' => [
        'nome' => 'Historico de Movimentacoes',
        'descricao' => 'Auditoria e trilha de movimentacoes',
        'route' => 'historico.index',
        'icone' => 'fa-clock-rotate-left',
        'cor' => 'violet',
        'ordem' => 8,
    ],
    '1008' => [
        'nome' => 'Configuracoes de Tema',
        'descricao' => 'Preferencias visuais e aparencia',
        'route' => 'settings.theme',
        'icone' => 'fa-palette',
        'cor' => 'teal',
        'ordem' => 9,
    ],
];
