-- Marcar como conferido os 13 smartphones Samsung
UPDATE patr SET FLCONFERIDO = 'S' WHERE NUPATRIMONIO BETWEEN 14934 AND 14946;

-- Verificar se foram marcados
SELECT NUPATRIMONIO, DEPATRIMONIO, FLCONFERIDO FROM patr WHERE NUPATRIMONIO BETWEEN 14934 AND 14946 ORDER BY NUPATRIMONIO;
